### ISSUE TITLE
WebpackOptionsValidationError when running readme instructions

### ISSUE THREAD

**Issue by JamieMason** [faceyspacey/universal-demo#50]
Environment:

```
$ node -v
v10.15.0

$ yarn -v
1.16.0
```

Steps to reproduce:

```
git clone https://github.com/faceyspacey/universal-demo.git
cd universal-demo
yarn
yarn start
```

Output:

```
$ yarn start
yarn run v1.16.0
$ npm run clean && cross-env NODE_ENV=development node server/index.js
npm WARN lifecycle The node binary used for scripts is /var/folders/0b/170t6klx7818k1y4y8pnzmj81c4w38/T/yarn--1562664774685-0.5515464088503916/node but npm is using /Users/jmn42/.nvm/versions/node/v10.15.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> flush-requires-boilerplate-webpack-chunknames@3.0.0 clean /Users/jmn42/Dev/tmp/universal-demo
> rimraf buildClient buildServer

/Users/jmn42/Dev/tmp/universal-demo/node_modules/webpack/lib/webpack.js:31
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].module.rules[1].use should be one of these:
   non-empty string | function | object { ident?, loader?, options?, query? } | function | [non-empty string | function | object { ident?, loader?, options?, query? }]
   -> Modifiers applied to the module when rule is matched
   Details:
    * configuration[0].module.rules[1].use[0] has an unknown property 'hot'. These properties are valid:
      object { ident?, loader?, options?, query? }
    * configuration[0].module.rules[1].use[0] has an unknown property 'reloadAll'. These properties are valid:
      object { ident?, loader?, options?, query? }
    at webpack (/Users/jmn42/Dev/tmp/universal-demo/node_modules/webpack/lib/webpack.js:31:9)
    at Object.<anonymous> (/Users/jmn42/Dev/tmp/universal-demo/server/index.js:28:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JamieMason** [comment]
Rolling back by one commit fixes it, so the latest commit is the likely cause.

```
git reset --soft HEAD~1
git reset --hard
git clean -dfX
yarn
yarn start
```

**Comment by chin2km** [comment]
Same. Couldnt start the application. Node 10.16.0
